# Generated by Django 6.0.2 on 2026-02-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['sender', 'timestamp'], name='core_transa_sender__f9695e_idx'),
        ),
    ]
